In [173]:
import numpy as np
import pandas as pd
from sklearn import tree

input_file = "C:\\Users\\pablo.ardiles\\Documents\\superliga\\all-matches.csv"
df = pd.read_csv(input_file, header = 0)

In [174]:
df.head()

ID  Col DayOfWeek          Date   Time  Col.1            TeamLocal  \
0  1314416    1    Friday   Aug 10 2018  23:00    895      Velez Sarsfield   
1  1314421    1  Saturday   Aug 11 2018  01:00   4735                Tigre   
2  1314420    1  Saturday   Aug 11 2018  17:15    896          Gimnasia LP   
3  1314425    1  Saturday   Aug 11 2018  19:30    892                Union   
4  1314417    1  Saturday   Aug 11 2018  21:45   9310  Patronato de Parana   

   RedCardLocal  Col.2           TeamVisit    ...      Col.6  Col.7  Col.8  \
0             0    902    Newells Old Boys    ...          1      0      1   
1             0    906         San Lorenzo    ...          0      0      1   
2             0    907  Argentinos Juniors    ...          1      0      1   
3             0   6145            Aldosivi    ...          1      0      1   
4             0    891               Colon    ...          0      0      1   

  Col.9  Col.10     Season            Col.11     Col.12     Col.13     Col.14  
0     0       0  2018/2019  Primera División  Argentina  Argentina  Argentina  
1     0       0  2018/2019  Primera División  Argentina  Argentina  Argentina  
2     0       0  2018/2019  Primera División  Argentina  Argentina  Argentina  
3     0       0  2018/2019  Primera División  Argentina  Argentina  Argentina  
4     0       0  2018/2019  Primera División  Argentina  Argentina  Argentina  

[5 rows x 27 columns]

In [175]:
features = ['TeamLocal','TeamVisit']
features

['TeamLocal', 'TeamVisit']

In [176]:
#d = {'Aldosivi': 0, 'Argentinos Juniors': 1, 'Atletico Tucuman': 2, 'Banfield': 3, 'Belgrano': 4, 'Boca Juniors': 5, 'Colon': 6, 'Defensa y Justicia': 7, 'Estudiantes': 8, 'Gimnasia LP': 9, 'Godoy Cruz': 10, 'Huracan': 11, 'Independiente': 12, 'Lanus': 13, 'Newells Old Boys': 14, 'Patronato de Parana': 15, 'Racing Club': 16, 'River Plate': 17, 'Rosario Central': 18, 'San Lorenzo': 19, 'San Martin de Tucuman': 20, 'San Martin San Juan': 21, 'Talleres': 22, 'Tigre': 23, 'Union': 24, 'Velez Sarsfield': 25}
d = {'Racing Club': 0, 'Defensa y Justicia': 1, 'Boca Juniors': 2, 'River Plate': 3, 'Atletico Tucuman': 4, 'Velez Sarsfield': 5, 'Independiente': 6, 'Union': 7, 'Lanus': 8, 'Talleres': 9, 'Tigre': 10, 'Huracan': 11, 'Aldosivi': 12, 'Godoy Cruz': 13, 'Newells Old Boys': 14, 'Banfield': 15, 'Estudiantes': 16, 'Rosario Central': 17, 'Gimnasia LP': 18, 'Patronato de Parana': 19, 'Colon': 20, 'San Lorenzo': 21, 'San Martin San Juan': 22, 'Argentinos Juniors': 23, 'San Martin de Tucuman': 24, 'Belgrano': 25}
df['TeamLocal'] = df['TeamLocal'].map(d)
df['TeamVisit'] = df['TeamVisit'].map(d)

df.head()

ID  Col DayOfWeek          Date   Time  Col.1  TeamLocal  \
0  1314416    1    Friday   Aug 10 2018  23:00    895          5   
1  1314421    1  Saturday   Aug 11 2018  01:00   4735         10   
2  1314420    1  Saturday   Aug 11 2018  17:15    896         18   
3  1314425    1  Saturday   Aug 11 2018  19:30    892          7   
4  1314417    1  Saturday   Aug 11 2018  21:45   9310         19   

   RedCardLocal  Col.2  TeamVisit    ...      Col.6  Col.7  Col.8 Col.9  \
0             0    902         14    ...          1      0      1     0   
1             0    906         21    ...          0      0      1     0   
2             0    907         23    ...          1      0      1     0   
3             0   6145         12    ...          1      0      1     0   
4             0    891         20    ...          0      0      1     0   

   Col.10     Season            Col.11     Col.12     Col.13     Col.14  
0       0  2018/2019  Primera División  Argentina  Argentina  Argentina  
1       0  2018/2019  Primera División  Argentina  Argentina  Argentina  
2       0  2018/2019  Primera División  Argentina  Argentina  Argentina  
3       0  2018/2019  Primera División  Argentina  Argentina  Argentina  
4       0  2018/2019  Primera División  Argentina  Argentina  Argentina  

[5 rows x 27 columns]

In [177]:
scoreMatch = df[["ScoreTeamLocal","ScoreTeamVisit"]]
matches = df[features]
clf = tree.DecisionTreeClassifier()
clf = clf.fit(matches,scoreMatch)

In [178]:
from IPython.display import Image  
from sklearn.externals.six import StringIO  
import pydotplus

dot_data = StringIO()  
tree.export_graphviz(clf, out_file=dot_data,  
                         feature_names=features)  
graph = pydotplus.graph_from_dot_data(dot_data.getvalue())  
Image(graph.create_png()) 

In [194]:
from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier(n_estimators=10)
clf = clf.fit(matches, scoreMatch)

print ('- Pronostico Superliga Fecha 25 -\n')
#-----------------------------
matchOfTheDay = ['Belgrano', 'Godoy Cruz']
print (matchOfTheDay[0] + " vs " + matchOfTheDay[1])
matchOfTheDay[0] = d[matchOfTheDay[0]]
matchOfTheDay[1] = d[matchOfTheDay[1]]
prediction = clf.predict([matchOfTheDay])
print (prediction)
#-----------------------------
matchOfTheDay = ['Patronato de Parana', 'Argentinos Juniors']
print (matchOfTheDay[0] + " vs " + matchOfTheDay[1])
matchOfTheDay[0] = d[matchOfTheDay[0]]
matchOfTheDay[1] = d[matchOfTheDay[1]]
prediction = clf.predict([matchOfTheDay])
print (prediction)
#-----------------------------
matchOfTheDay = ['River Plate', 'Tigre']
print (matchOfTheDay[0] + " vs " + matchOfTheDay[1])
matchOfTheDay[0] = d[matchOfTheDay[0]]
matchOfTheDay[1] = d[matchOfTheDay[1]]
prediction = clf.predict([matchOfTheDay])
print (prediction)
#-----------------------------
matchOfTheDay = ['San Martin San Juan', 'Talleres']
print (matchOfTheDay[0] + " vs " + matchOfTheDay[1])
matchOfTheDay[0] = d[matchOfTheDay[0]]
matchOfTheDay[1] = d[matchOfTheDay[1]]
prediction = clf.predict([matchOfTheDay])
print (prediction)
#-----------------------------
matchOfTheDay = ['San Martin de Tucuman', 'San Lorenzo']
print (matchOfTheDay[0] + " vs " + matchOfTheDay[1])
matchOfTheDay[0] = d[matchOfTheDay[0]]
matchOfTheDay[1] = d[matchOfTheDay[1]]
prediction = clf.predict([matchOfTheDay])
print (prediction)
#-----------------------------
matchOfTheDay = ['Aldosivi', 'Boca Juniors']
print (matchOfTheDay[0] + " vs " + matchOfTheDay[1])
matchOfTheDay[0] = d[matchOfTheDay[0]]
matchOfTheDay[1] = d[matchOfTheDay[1]]
prediction = clf.predict([matchOfTheDay])
print (prediction)
#-----------------------------
matchOfTheDay = ['Velez Sarsfield', 'Lanus']
print (matchOfTheDay[0] + " vs " + matchOfTheDay[1])
matchOfTheDay[0] = d[matchOfTheDay[0]]
matchOfTheDay[1] = d[matchOfTheDay[1]]
prediction = clf.predict([matchOfTheDay])
print (prediction)
#-----------------------------
matchOfTheDay = ['Banfield', 'Newells Old Boys']
print (matchOfTheDay[0] + " vs " + matchOfTheDay[1])
matchOfTheDay[0] = d[matchOfTheDay[0]]
matchOfTheDay[1] = d[matchOfTheDay[1]]
prediction = clf.predict([matchOfTheDay])
print (prediction)
#-----------------------------
matchOfTheDay = ['Huracan', 'Atletico Tucuman']
print (matchOfTheDay[0] + " vs " + matchOfTheDay[1])
matchOfTheDay[0] = d[matchOfTheDay[0]]
matchOfTheDay[1] = d[matchOfTheDay[1]]
prediction = clf.predict([matchOfTheDay])
print (prediction)
#-----------------------------
matchOfTheDay = ['Racing Club', 'Defensa y Justicia' ]
print (matchOfTheDay[0] + " vs " + matchOfTheDay[1])
matchOfTheDay[0] = d[matchOfTheDay[0]]
matchOfTheDay[1] = d[matchOfTheDay[1]]
prediction = clf.predict([matchOfTheDay])
print (prediction)
#-----------------------------
matchOfTheDay = ['Rosario Central', 'Independiente' ]
print (matchOfTheDay[0] + " vs " + matchOfTheDay[1])
matchOfTheDay[0] = d[matchOfTheDay[0]]
matchOfTheDay[1] = d[matchOfTheDay[1]]
prediction = clf.predict([matchOfTheDay])
print (prediction)
#-----------------------------


- Pronostico Superliga Fecha 25 -

Belgrano vs Godoy Cruz
[[ 0.  0.]]
Patronato de Parana vs Argentinos Juniors
[[ 3.  0.]]
River Plate vs Tigre
[[ 1.  1.]]
San Martin San Juan vs Talleres
[[ 0.  0.]]
San Martin de Tucuman vs San Lorenzo
[[ 0.  0.]]
Aldosivi vs Boca Juniors
[[ 0.  0.]]
Velez Sarsfield vs Lanus
[[ 2.  0.]]
Banfield vs Newells Old Boys
[[ 1.  0.]]
Huracan vs Atletico Tucuman
[[ 0.  0.]]
Racing Club vs Defensa y Justicia
[[ 2.  2.]]
Rosario Central vs Independiente
[[ 2.  2.]]
